import re
import time
import streamlit as st
from zerogpt_api import check_ai_content
import common
import json

def display_highlighted_text(detection_result, html_view=False):
    params = st.query_params
    mode = params.get("mode", None)
    record_id = params.get("id", None)

    data = detection_result.get("data", {})
    ai_segments = data.get("h", [])
    input_text = data.get("input_text", "")
    fake_percentage = data.get("fakePercentage", 0)
    feedback = data.get("feedback", "No feedback provided.")
    is_human = data.get("isHuman", 0)
    ai_words = data.get("aiWords", 0)
    text_words = data.get("textWords", 0)

    # Highlight AI-generated segments
    highlighted_text = input_text
    for term in ai_segments:
        pattern = re.escape(term)
        highlighted_text = re.sub(
            pattern,
            f"<mark style='background-color: yellow; color: black;'>{term}</mark>",
            highlighted_text,
            flags=re.IGNORECASE
        )

    # Initialize session state
    st.session_state.setdefault("show_editor", False)
    st.session_state.setdefault("editable_text", highlighted_text)
    st.session_state.setdefault("record_id", record_id)
    # --- Section Header ---
    st.markdown("### 📝 Detected Content")
    # VIEW MODE
    safe_text = highlighted_text.replace("\n", "<br/>")
    #
    if html_view:
        safe_text = common.ai_to_html(safe_text)
    st.markdown(f"""
        <div style="line-height:1.6;">
        {safe_text}
        </div>
        """, unsafe_allow_html=True)
    st.markdown(
        """
        <div style="color: black;padding:15px;border-radius:10px; background-color:yellow;font-weight: bold;margin-top: 15px;">
            Yellow Highlighted text is generated by AI.
        </div>
        """, unsafe_allow_html=True)
    st.markdown("---")
    st.subheader("🧩 AI Detection Results")

    if int(is_human) >= 85:
        label = "🧍 Human-Written"
    else:
        label = "🧠 AI-Generated"


    if int(is_human) >= 85:
        color = "green"
    else:
        color = "red"

    if int(is_human) >= 85:
        bgcolor = "#cadeca"
    else:
        bgcolor = ""

    st.markdown(
        f"""
        <div style="padding:15px;border-radius:10px;background-color:{bgcolor};">
            <h4 style="margin:0;">Prediction: <span style="color:{color};">{label}</span></h4>
            <p style="margin:5px 0;"><b>Feedback:</b> {feedback}</p>
            <p style="margin:5px 0;"><b>AI Probability:</b> {fake_percentage:.2f}%</p>
            <p style="margin:5px 0;"><b>Total Words:</b> {text_words} |
            <b>AI Words:</b> {ai_words} |
            <b>Estimated Human Words:</b> {max(text_words - ai_words, 0)}</p>
        </div>

        """,
        unsafe_allow_html=True,
    )
    # --- Detection Summary (always visible) ---
    # label = "🧠 AI-Generated" if is_human == 0 else "🧍 Human-Written"
    # color = "red" if is_human == 0 else "green"
    st.markdown(
        """
        <style>
            .stProgress > div > div > div > div {
                background-color: yellow;
            }

            /* Style for the empty part of the progress bar */
            .stProgress > div > div > div {
                background-color: green;
            }
        </style>""",
        unsafe_allow_html=True
    )
    st.progress(min(max(fake_percentage / 100, 0), 1))

    # --- Highlighted / Editable Section ---

    # if not st.session_state.show_editor:
    #     if st.button("✏️ Edit Detected Content"):
    #         st.session_state.show_editor = True
    #         st.rerun()
    # else:
    #     # EDIT MODE
    #     st.markdown("---")
    #     st.markdown(
    #         """
    #         <div style='font-size:22px;'><b style="text-decoration: underline;">Content Editor:</b></div>""",
    #         unsafe_allow_html=True
    #     )
    #     edited_text = st.text_area(
    #         "",
    #         value=st.session_state.editable_text.replace(
    #             "<mark style='background-color: yellow; color: black;'>", ""
    #         ).replace("</mark>", ""),
    #         height=400,
    #     )

    #     col1, col2 = st.columns(2)
    #     with col1:
    #         if st.button("🔁 Recheck with ZeroGPT"):
    #             with st.spinner("Rechecking edited content..."):
    #                 new_detection = check_ai_content(edited_text)
    #                 st.session_state.detection_result = new_detection
    #                 st.session_state.show_editor = False
    #                 st.session_state.editable_text = edited_text
    #                 record_id = st.session_state.record_id
    #                 if record_id:
    #                     common.update_output_to_db(
    #                     record_id,
    #                     final_output=edited_text,
    #                     detection_result=json.dumps(new_detection)
    #                     )
    #                 else:
    #                     st.warning("⚠️ No record ID found in URL parameters. Changes not saved to database.")
    #                     time.sleep(5)
    #                 st.success("✅ Recheck complete!")
    #                 st.rerun()
    #     with col2:
    #         if st.button("❌ Cancel Edit"):
    #             st.session_state.show_editor = False
    #             st.rerun()
